twreporter/twreporter-npm-packages

packages/react-components/CHANGELOG.md, packages/react-components/package.json, packages/react-components/src/bookmark-widget/index.js
After this update, the component will take `slug` and `host` from window, and won't use them when server-side rendering.
=> Fix bookmark-widget ssr error

CHANGELOG.md, dev/makefiles.test.js, dev/source.makefile, makefile, package.json, packages/core/makefile, packages/index-page/makefile, packages/react-article-components/makefile, packages/react-components/makefile
- Add makefile test to ensure all package makefiles have the same content as source.
- Add `cp-make` command to copy source makefile to all package folders
- Update makefiles in packages
- Start environment setting versioning
KanbanFlow tasks:
- [Add Jest test to ensure all makefiles have the same content](https://kanbanflow.com/t/hgLaVAy5)
- [Add make script at root to create makefile for each package folder](https://kanbanflow.com/t/yzrV8bDD)
=> Makefile enhancement

packages/react-components/CHANGELOG.md, packages/react-components/package.json, packages/react-components/src/donation-link-with-utm.js
Users might not click the donation link directly.
They might right click the donation link  and click `Open Link in New Tab` or `Open Link in New Window` ..., etc.
In previous implementation, we handle browser navigation on click event. However, it won't work if users does not left click the link.
Use `this.state.isClient` to update the donation link after mounting on client side.
=> [react-components] update `src/donation-link-with-utm.js`, pure func -> extends React.PureComponent

packages/react-article-components/CHANGELOG.md, packages/react-article-components/src/components/article-page.js, packages/react-article-components/src/components/body/brief.js
https://kanbanflow.com/t/2DQ6UGQE
create a new project named `*.twreporter.org` in https://fonts.adobe.com/my_fonts#web_projects-section.
`ff-tisa-web-pro` (new added in this change)
- `Regular: 400`
- `Medium: 600`
- `Bold: 700`
`source-han-sans-tranditional`
- `ExtraLight: 100`
- `Normal: 300`
- `Bold: 700`
`source-han-serif-tc`
- `SemiBold: 600`
According to gina's mockup(https://zpl.io/2yPlg8q), `font-weight` of `ff-tisa` is different from  `source-han-sans-tranditional` (as you can see the differences above).
In current implementation, it is hard to set different `font-weight` on Chinese and English texts.
Therefore, we use `font-weight` of Chinese to send requests to typekit to get English texts.
We let typekit to do the fallback, typekit will try to get the closest value, such as …
=> [react-article-components] `ff-tisa` for english text

packages/react-article-components/CHANGELOG.md, packages/react-article-components/package.json, packages/react-article-components/src/components/article-page.js, packages/react-article-components/src/components/body/index.js
https://kanbanflow.com/t/2E4GmzdB
https://github.com/twreporter/twreporter-npm-packages/commit/011316536d030196293970b49dfc21bc88b25205 is to fix `image`, `slideshow` ...etc multimedia element not to fill 100% viewport width.
=> Make `center-small` alignment fills 100% viewport width on mobile

packages/react-article-components/CHANGELOG.md, packages/react-article-components/src/components/body/embedded-code.js
https://kanbanflow.com/t/fp8ce375
=> [react-article-components] fix embedded img not centered if not big enough

packages/index-page/CHANGELOG.md, packages/index-page/package.json, packages/index-page/src/components/animations/section-animation-wrapper.js
[Kanban Flow Card](https://kanbanflow.com/t/H9a4fnka)
=> [Bug] Disable `fireOnRapidScroll` in Waypoint of index page section to keep anchor correct

packages/core/CHANGELOG.md, packages/core/package.json, packages/core/src/utils/sign-in-href.js, packages/index-page/CHANGELOG.md, packages/index-page/package.json, packages/react-article-components/CHANGELOG.md, packages/react-article-components/package.json, packages/react-components/CHANGELOG.md, packages/react-components/package.json, packages/universal-header/CHANGELOG.md, packages/universal-header/package.json
Problem description:
Since we are going to test on `next` release branch and `signInHref` in `sigin-in-href.js` doesn't have `next` branch as an attribute, font-end server crashes at [this line](https://github.com/twreporter/twreporter-npm-packages/blob/372554322a357cb2bef99f64586e376a13992b8b/packages/core/src/utils/sign-in-href.js#L38).
I propose to maintain only one constant file (`request-origins.js` ) to keep the origin information of different release branch.
Ref: [Kanban Flow Card](https://kanbanflow.com/t/BJCoy4EG)
=> [core] Use `request-origins.js` constants in `sigin-in-href.js` 

packages/universal-header/package.json, packages/universal-header/src/actions/auth.js, packages/universal-header/src/actions/error-action-creators.js, packages/universal-header/src/constants/action-types.js, packages/universal-header/src/reducers/auth.js, packages/universal-header/src/reducers/index.js, packages/universal-header/src/standalone-header.js, packages/universal-header/src/utils/jwt.js
The root cause is that the latest `@twreporter/redux/lib/store/createStore` return a `Promise` rather than a redux store instance.
Decouple `@twreporter/redux`. 
Maintain redux store/actions/reducers by `@twreporter/universal-header` itself.
=> fix(universal-header): standalone header cannot work normally

packages/react-components/src/footer/index.js
This patch removes `max-height` on mobile since it shows body's
background instead of white(footer's background color) when the
max-height is exceeded
=> fix(footer): body's background shows when exceeds max-height

packages/react-article-components/src/components/body/embedded-code.js
- dispatch window load event when each script is load => only dispatch window load event once after all scripts are load
- append script to DOM tree one by one => update DOM tree once with fragment
=> update embedded component of react-article-components

packages/react-article-components/src/components/aside/tools.js
First of all, huge thanks for this great website you built. 
As a Twitter user and a reader of The Reporter, it could be convenient for readers to share an article by just clicking the Twitter share icon and not doing anything else.
But surprisingly, I found the website only provides only the link to Twitter Web Intent API, so readers have to add the title manually, which is not convenient for readers who would like to share the article like me.
I luckily found the source code and decided to contribute. I hope this won't interrupt your work.
Thank you.
=> feature: added text and via to Twitter share link

packages/react-article-components/dev/entry.js, packages/react-article-components/dev/mock-post.json, packages/react-article-components/src/components/article-page.js, packages/react-article-components/src/components/related/index.js, packages/react-article-components/src/components/related/list.js
Let consumers to pass `loadMoreRelateds` to load more related posts,
and `hasMoreRelateds` to decide if to show load more button.
- article-page:
- props added: hasMoreRelateds
- props added: loadMoreRelateds
- related:
- props added: hasMore
- props added: loadMore
- dev/entry:
- simulate load more related posts
=> feat(react-article-components): update Relateds props

packages/react-article-components/src/components/article-page.js, packages/react-article-components/src/components/body/index.js, packages/react-components/src/table-of-contents/index.js
We create `TOCManager` instance in each render of `Body` component,
and pass that instance into every `TOC.React.Anchor` as props.
The problem shows up when we rerender `Body`.
When we rerender `Body`, there are several steps happen:
1. recreate a new instance of `TOCManager`
2. pass the tocManager instance to every `Anchor`
3. `Anchor` won't be re-initialized if `key` prop not change
4. Due to step 3., `Anchors` information won't be stored into the tocManager instance
5. `TOC.React.TableOfContents` will dissapears after rerendering.
Create the instance of `TOCManager` only once.
Therefore, `Anchors` information won't disappear after `Body` rerenders.
=> fix: toc disappears after article body rerenders

packages/redux/src/reducers/related-posts-of.js
Editors report that we render duplicate related posts.
=> fix(redux): deduplicate related posts

packages/redux/src/reducers/related-posts-of.js
After [PR: fix(redux): deduplicate related posts](https://github.com/twreporter/twreporter-npm-packages/pull/157) merged,
the duplicate related posts are removed.
However, in some situations, it will lack of one post like following example.
The reason is because that missing post is selected post itself. 
Hence it will be omitted while rendering.
This PR is to filter selected post itself from its related posts array.
=> fix(redux): filter selected post itself from its related posts

packages/react-components/src/footer/content.js
kanban flow card: 
[story-39][task-1] 在 footer 「基金會新聞專區」上方新增一個超連結「Podcast節目列表」，連結到 [podcast 節目清單頁](https://www.twreporter.org/a/podcast-list)
=> Add podcast list link to footer

packages/react-article-components/src/components/aside/tools.js
This patch adds the id tags to the social share icons(fb/twitter/line)
so that non-dev colleagues can leverage the CSS selector on GTM to
selector the icons independently.
=> refactor(react-article-components): add id tag to the aside tool

packages/universal-header/src/components/header.js, packages/universal-header/src/components/icons.js, packages/universal-header/src/constants/services.js, packages/universal-header/src/containers/header.js
[Summary]
bookmark icon only show when login & modify desktop icon show/hide flow
[Related story]
twreporter-73
[Scope]
universal-header
[Change]
Before change, Icons component will always render bookmark icon & determine to render login/logout inside itself.
After change, header container component will determine which icons to render, then pass it to Icons component.
=> refactor(universal-header): modify desktop icon show/hide flow

packages/errors/src/helpers/print.js
If the stack lines of error are less than trimmedCount, the whole stack lines will be deleted.
This patch remains the first line of error stack.
=> refactor(errors): remain the first line of stack trace

packages/react-article-components/src/components/leading/normal.js
Address [TWREPORTER-158](https://twreporter-org.atlassian.net/browse/TWREPORTER-158).
This patch updates topic label style for article page to increase margin
between header and topic label for normal article page.
=> refactor: update topic label style for article page

packages/react-article-components/src/constants/position-z-index.js
- current z-index: toc > web push > universal header
=> fix: article table of content should be top of everything

packages/react-article-components/src/components/article-page.js, packages/react-article-components/src/components/aside/mobile-aside.js, packages/react-article-components/src/components/table-of-contents/index.js
**combine jira ticket [219](https://twreporter-org.atlassian.net/jira/software/c/projects/TWREPORTER/boards/7?modal=detail&selectedIssue=TWREPORTER-219), [220](https://twreporter-org.atlassian.net/jira/software/c/projects/TWREPORTER/boards/7?modal=detail&selectedIssue=TWREPORTER-220) to remove duplicate css**
1. 219: 套用media print使文章左側的索引在print mode不會顯示
* dev可測的文章: http://localhost:3000/a/child-health-care-save-their-lives
2. 220:
* mq似乎不能在print mode中辨認device, 所以在列印時還是會render右下的mobile aside, 而且要reproduce bug要header的評論/專題/攝影…這個list有縮放(scroll down)再按列印(cmd + p)
=> fix: disappear mobile aside/index in print mode

packages/index-page/src/components/editor-picks.js
This patch set `line-break: anywhere;` in title of editor picks to avoid
unexpected line break caused by punctuation characters.
=> fix: update line-break property to avoid unexpected line break

packages/react-article-components/package.json, packages/react-article-components/src/components/body/audio/audio-provider.js, yarn.lock
Address [TWREPORTER-317](https://twreporter-org.atlassian.net/browse/TWREPORTER-317)
This patch updates howler config for large audio files so that users
don't have to wait for the full file to be downloaded and decoded
before playing.
Also, set 'preload' to 'metadata' to preload the file's metadata
to get its duration without download the entire file.
ref: 
- html5: https://github.com/goldfire/howler.js#html5-boolean-false
- preload: https://github.com/goldfire/howler.js#preload-booleanstring-true
=> refactor: update howler config for large audio files

packages/react-components/src/bookmark-list/bookmarks.js, packages/react-components/src/bookmark-list/empty-guide.js, packages/react-components/src/bookmark-list/index.js, packages/react-components/src/bookmark-list/stories/bookmark.stories.js, packages/react-components/src/bookmark-list/stories/empty-guide.stories.js, packages/react-components/src/button/index.js
This patch address [TWREPORTER-291](https://twreporter-org.atlassian.net/browse/TWREPORTER-291).
- add empty guide component & story
For testing, please test with `twreporter-react` [#2122](https://github.com/twreporter/twreporter-react/pull/2122).
=> feat: add bookmark list empty guide

packages/react-components/src/bookmark-list/empty-guide.js, packages/react-components/src/button/components/iconButton.js, packages/react-components/src/button/components/iconWithTextButton.js, packages/react-components/src/button/components/pillButton.js, packages/react-components/src/button/stories/pillButton.stories.js
- pillButton: add `iconComponent` prop
- iconButton, iconWithTextButton: fix iconComponent propTypes
- bookmark-list/empty-guide: fix style
Note: After discuss with designer, pillButton should accept different icon, thus change pillButton's spec in this patch.
=> fix: add pillButton iconComponent prop & fix empty bookmark style

packages/core/src/constants/font.js
Address [TWREPORTER-318](https://twreporter-org.atlassian.net/browse/TWREPORTER-318)
https://github.com/twreporter/twreporter-react/pull/2148 is required by this change.
This patch updates fonts due to webfont changes from adobe fonts to
google fonts.
=> refactor: change fonts

packages/react-article-components/src/components/article-page.js, packages/react-article-components/src/components/aside/mobile-tool-bar.js
- [363](https://twreporter-org.atlassian.net/browse/TWREPORTER-363), [364](https://twreporter-org.atlassian.net/browse/TWREPORTER-364): fix style
- [361](https://twreporter-org.atlassian.net/browse/TWREPORTER-361): enter topic page when click `back to topic`
- [356](https://twreporter-org.atlassian.net/browse/TWREPORTER-356): bookmark text should change as status
- [357](https://twreporter-org.atlassian.net/browse/TWREPORTER-357): rename ToolBar to DesktopToolBar as it remove in mobile/tablet
- [360](https://twreporter-org.atlassian.net/browse/TWREPORTER-360): add custom hook to listen click event
- [366](https://twreporter-org.atlassian.net/browse/TWREPORTER-366): add `behavior: smooth` to scrollToView option
- [367](https://twreporter-org.atlassian.net/browse/TWREPORTER-367): inject …
=> fix: fix defect

packages/react-article-components/src/components/aside/desktop-tools.js, packages/react-article-components/src/components/aside/mobile-tool-bar.js
- TWREPORTER-372
- add `add-bookmark` & `remove-bookmark` id in order to exclude remove bookmark behavior on GTM trigger
- TWREPORTER-398
- add releaseBranch for desktop-tools icon
- pop out snackbar asynchronously
=> fix: add id for bookmark & fix icon releaseBranch

packages/react-article-components/src/components/aside/metadata.js
修正 [jira #328](https://twreporter-org.atlassian.net/browse/TWREPORTER-328): 如果沒有子分類，應該要顯示`全部`，並且點擊後連結到主分類
=> fix: fix empty subcategory part

packages/react-article-components/src/components/body/embedded-code.js, packages/react-article-components/src/constants/position-z-index.js
Address [TWREPORTER-420](https://twreporter-org.atlassian.net/browse/TWREPORTER-420)
This patch updates embeded code block z-index for embeded code from
@twreporter packages to let components in @twreporter/orangutan-monorepo
on top of toolbar.
=> refactor(react-article-components): set embeded code z-index

packages/core/src/constants/feature-flag.js
This patch disables feature toggle for new info structure to test other feature in staging.
=> chore(core): disable feature toggle for new info structure

packages/react-components/.storybook/preview.js
The storybook can't show any content and continuously loading.
I found that the console in dev tool show the error message `Uncaught ReferenceError: INITIAL_VIEWPORTS is not defined`
Because `INITIAL_VIEWPORTS` is removed in #313, the config can't be loaded correctly
=> fix: storybook missing config

packages/core/src/constants/font.js
Address [Reduce unused CSS: google font CSS link](https://app.asana.com/0/0/1202942985879129/f)
This patch updates the font 'Noto Serif TC' to 'source-han-serif-tc' since the third party web fonts changes from google font to adobe font due to performance issue (suggested by PageSpeed Insights).
=> refactor: update font 'Noto Serif TC' to 'source-han-serif-tc'

packages/core/src/constants/category-set.js, packages/react-article-components/src/components/aside/metadata.js
fix
[[defect] 點擊文章頁 meta data 的分類/子分類時，無法正確跳轉到對應頁面](https://app.asana.com/0/1202961977949746/1203964075873151/f)
[[defect] keystone 設定的分類組合未完整顯示於文章頁](https://app.asana.com/0/1202961977949746/1203964075873152/f)
=> fix: fix category link issue & add error handling

packages/core/src/constants/category-set.js
twreporter-react升級node到16除了要改circle ci config外應該還要改其他地方, 而且最好需要測試, 而且url.parse那個warning改掉後routing會有問題, 還需要其他處理, 先把Object.fromentries替換成相容的寫法
=> fix: replace Object.fromentries() to avoid version compatiblity issue

packages/core/src/constants/category-set.js, packages/react-components/src/listing-page/components/list.js, packages/redux/src/reducers/__test__/index-page.test.js, packages/redux/src/reducers/index-page.js, packages/universal-header/src/components/tab-bar.js, packages/universal-header/src/utils/links.js
This patch fix following defects:
- [`[defect] 首頁議題區塊只顯示 7 個區塊，少了政治社會`](https://app.asana.com/0/0/1203964075873158/f)
- [`[defect] 主網站：分類頁的 title bar 與下面的文章 margin: tablet 應為 32px，mobile 應為 24px`](https://app.asana.com/0/0/1203964971392538/f)
- [`[defect] 主網站：最新頁的 title bar 與下面的文章 margin: tablet 應為 32px，mobile 應為 24px`](https://app.asana.com/0/0/1203964971392530/f)
- [`[defect] 最新頁：在最新頁點選其他時事時，tab bar 的最新 tab 應該要 active state（變成紅色）`](https://app.asana.com/0/0/1203964971392539/f)
=> fix: category politics and society path typo

packages/universal-header/src/components/header.js
This patch fix [[defect] mobile header 的 logo 沒有置中](https://app.asana.com/0/1203699264568808/1203955893209717/f)
=> fix: mobile header logo align center

packages/react-components/src/listing-page/components/list.js
[[defect] tag 頁的文章沒有出現文章主分類](https://app.asana.com/0/1203699264568808/1204362012792364/f)
Same list has been used in category page which should not show `category` string, thus add `showCategory` prop to determine show or not.
N/A
=> fix: add `showCategory` prop for List component

packages/index-page/src/components/editor-picks-old.js, packages/index-page/src/index.js
[[defect] 首頁編輯精選區塊沒有出現分類組合](https://app.asana.com/0/0/1204529009740269/f)
N/A
=> fix: editor pick section should show category_set info

packages/react-components/package.json, packages/universal-header/src/components/tab-bar.js, yarn.lock
- fix tab bar button theme
- `transparent` page still use `normal` theme buttons
- remove useless dependency `material-symbols`
- import it in `twreporter-react` & `membership-fe`
=> fix: tab bar icon theme

packages/universal-header/src/components/action-button-item.js, packages/universal-header/src/components/action-button-item.stories.js, packages/universal-header/src/components/action-button.js
[20230512 transparent 的 mobile sidemenu 的按鈕看不到（因為是 transparent theme，但應該用 normal 就好）](https://app.asana.com/0/1203983432530614/1204588802643715/f)
=> fix: fix action button theme

packages/universal-header/src/utils/links.js
[[defect] 未登入時，header member icon 無法正常導入至登入頁，而是 404
](https://app.asana.com/0/0/1204968662726636/f)
N/A
=> fix: signin path typo

packages/universal-header/src/components/action-button-item.js, packages/universal-header/src/components/action-button.js
[[defect] hd, desktop - sidemenu → 訂閱電子報，到電子訂閱頁後應該要收起 sidemenu
](https://app.asana.com/0/0/1204966623570383/f)
[[defect] tablet, mobile - menu → 訂閱電子報，到電子訂閱頁後應該要收起 menu](https://app.asana.com/0/0/1204966623570385/f)
N/A
=> fix: close hamburger menu after clicking action button

packages/redux/src/reducers/entities.js
在首頁的「議題」專區，「政治社會」分類的新聞沒有出現。
請見附圖：
=> fix(redux): `politics-and-society` category not shown on index page

packages/react-components/src/listing-page/components/list.js
在數位敘事的 listing page ( https://www.twreporter.org/tag/630f029461ca4e07004ef530 ) 裡，多篇多媒體文章點擊後，文章沒有順利導到正確的網址；導致文章內容沒有正確呈現。
若該篇文章的 `style` 為 interactive 的話，其 url path 應該為 `/i/${post_slug}`，而非 `/a/${post_slug}`，而且點擊該篇文章連結時，要另開分頁。
程式碼裡有 typo，導致沒有正確判斷 post style。
=> fix(react-components): wrong url path for interactive posts

packages/react-components/src/mobile-member-role-card/index.js
[[defect] 會員卡的右邊標題應該靠右](https://app.asana.com/0/0/1205283044439410/f)
N/A
=> fix: member role card layout

.circleci/config.yml
[[工程] upgrade nodejs to v18
](https://app.asana.com/0/1203699264568808/1204298342406882/f)
- vercel deployment setting would also need to be updated after release
N/A
=> chore: upgrade node to v18.17.1 (LTS)

packages/react-components/src/input/components/text-field.js
[[defect] safari expired state 時，text field 會消失](https://app.asana.com/0/0/1205430118369584/f)
N/A
=> fix: safari input bottom border dissapear

packages/react-components/src/button/components/link.js
[[spec change] mobile 「再寄一次驗證碼」disabled 時不應該能被點擊](https://app.asana.com/0/0/1205517202465215/f)
N/A
=> fix: remove click effect when link disabled on mobile

packages/react-components/src/button/components/link.js, packages/react-components/src/button/index.js, packages/react-components/src/button/stories/link.stories.js, packages/react-components/src/text/paragraph.js
[[維運] 會員頁-電子報設定新增「少年報導者」
](https://app.asana.com/0/1203699264568808/1205728019440902/f)
- add `InheritLinkButton` component & story
-  `weight`, `font-size` would inherit from parent
- easy to use with in paragraph with other words
- change `text/paragraph` to `p` tag
N/A
=> feat: add `InheritLinkButton` component & story

packages/core/src/constants/feature-flag.js, packages/universal-header/src/utils/links.js
[[資訊架構] 子分類 empty state
](https://app.asana.com/0/1203699264568808/1206117666290864/f)
also enable `FOUNDATION_CATEGORY_SET` feature toggle for testing
N/A
=> fix: foundation link in spa

packages/universal-header/.storybook/main.js
[Vercel build failure](https://vercel.com/twreporter-npm-packages/twreporter-npm-packages-universal-header/2P17cM3syiwfNsdJCojjLG68E7eK). 
vercel 在部署 storybook 時，會把 twreporter-npm-packages 整個 repo clone 下來，跑 yarn install 安裝 dependencies。
但因為 twreporter-npm-packages 是 monorepo，npm workspaces 在安裝 packages/* 底下的 pkg 時，例如安裝 `packages/universal-header` 的 deps 時，npm workspaces 並不會真的安裝 `@twreporter/react-components` 和 `@twreporter/core`，反而是用 symlinks 的方式將 `node_modules/@twreporter/react-components` 指到 `packages/react-component` 目錄底下。
在 commit [feat: add useBookmark & useStore](https://github.com/twreporter/twreporter-npm-packages/commit/7fd48e521e659307b1b91a6b4acdfb4d0a2fd683) 之前，universal-header 雖然有標註 `@twreporter/react-components` 當作 deps，而 `@twreporter/react-components` 亦有標註 …
=> chore(universal-header): try to fix storybook deployment failure

packages/react-components/src/button/components/textButton.js
[[defect] card/general: text button size=small 時， icon 與 text 有 padding 4px](https://app.asana.com/0/0/1206371001801889/f)
=> fix: add margin between text and icon

packages/react-article-components/src/components/article-page.js
use first category name in `category_set` as bookmark category
`twreporter-react` repo also has utils function to address this issue ([ref](https://github.com/twreporter/twreporter-react/blob/3424cbb32b2588eb4caf5712161dd2a555c04b40/src/utils/bookmark.js#L16))
N/A
=> fix: use first category name in `category_set` for bookmark

packages/core/src/constants/color.js
[[維運]  網站顏色盤點 : 主網站](https://app.asana.com/0/1203699264568808/1206157706155674/f)
ref: [twreporter color](https://docs.google.com/spreadsheets/d/1-g8lEFgB4tbvXIunl0xOLfjsdlCghjohuvfiHZP0BGA/edit?usp=sharing)
N/A
=> fix: add `white_0.9` to colorOpacity

packages/react-components/src/mobile-member-role-card/index.js
[[survey] mobile 會員卡的 email 不需要底線、自動連結信箱](https://app.asana.com/0/1203699264568808/1206269062307371/f)
`<meta name="format-detection" content="email=no">` only works on ios safari
N/A
=> fix: prevent ios chrome email format detection

packages/react-article-components/src/components/body/image.js, packages/react-article-components/src/components/img-with-placeholder/index.js, packages/react-article-components/src/components/leading/fullscreen.js, packages/react-article-components/src/components/leading/normal.js, packages/react-article-components/src/components/leading/pink.js
Add the `clickable` prop to prevent triggering the `disable-scroll` class.
=> fix: add clickable prop for image

packages/react-article-components/src/components/body/embedded-code.js
slack msg: https://twreporter.slack.com/archives/C09N6TNN7/p1717123213877979
After upgrading react to v18, `EmbeddedCode` component becomes abnormal. One case is that `EmbeddedCode` will `executeScript()` twice; therefore, it will generate duplicate contents.
This patch is a workaround to avoid `executeScript()` twice.
=> fix(rac): update embedded-code.js. Avoid `executeScript()` twice

packages/react-components/src/footer/constants/links.js
[[維運] footer 超連結對象修改](https://app.asana.com/0/1203699264568808/1207466978658904/f)
N/A
=> fix: add missing `/` in url

packages/react-article-components/src/components/body/embedded-code.js, packages/react-article-components/src/components/leading/embedded.js
The `EmbeddedCode` component was wrapped with `Waypoint`, so if we return the `loading` component, it won't trigger a render.
=> fix: check embeddedCode exist and loading issue

packages/core/src/constants/font.js, packages/react-components/src/text/utils/webfonts.js
[[維運] 全站新增字體：豆腐烏體](https://app.asana.com/0/1203699264568808/1207840188252446/f)
- @nickhsine self-host font would be hosted in `https://www.twreporter.org/assets/font/`, thus we should delete the copy in `public.twreporter.org/fonts/` after release ([ref](https://github.com/twreporter/twreporter-npm-packages/blob/4fdc214fd7117dd0af4a323053dfdb2a77884247/packages/react-components/src/text/utils/webfonts.js#L13))
N/A
=> feat: add new sel-host font `tauhu-oo`

packages/react-article-components/src/components/leading/embedded.js
[[維運] embeded 滿版新增 place holder 畫面](https://app.asana.com/0/1203699264568808/1208371474585818/f)
`EmbeddedCode` component would fire `load` event on `window` after all script loaded.
and `handleIsLoaded` would be called when it start to load
N/A
=> fix: set loading false when embedded script loaded

packages/react-article-components/src/components/body/embedded-code.js, packages/react-article-components/src/components/leading/embedded.js
[[維運] embeded 滿版新增 place holder 畫面](https://app.asana.com/0/1203699264568808/1208371474585818/f)
- inline script would not fire `load` event after loaded, thus we need to dispatch `load` event mannually on the end of the inline script text
- also add `handleFinishLoaded` props for `Embedded` component to avoid misunderstanding of `handleLoaded` props
N/A
=> fix: dispatch load event for inline script

packages/react-article-components/src/components/body/embedded-code.js
[[hotfix] 使用 embedded 的文章無法多個顯示](https://app.asana.com/0/1203699264568808/1206138012362942/f)
- fix 2 js error when loading embedded scripts
- `hanldeFinishLoaded` is not a function
- `loadEvent` has been declared
N/A
=> fix: js error when loading embedded scripts
