twreporter/twreporter-npm-packages

packages/react-components/CHANGELOG.md
packages/react-components/package.json
yarn.lock

- @twreporter/redux: ^5.0.1 -> 5.0.2

Bump @twreporter/react-components version to v7.0.2

---

packages/core/CHANGELOG.md
packages/core/src/constants/external-links.js
packages/index-page/CHANGELOG.md
packages/index-page/package.json
packages/index-page/src/components/donation-box-section.js
packages/react-components/CHANGELOG.md
packages/react-components/package.json
packages/react-components/src/donation-link-with-utm.js
packages/react-components/src/footer/content.js

https://kanbanflow.com/t/mkh8MzGM

Donation link with utm query string

---

packages/react-article-components/CHANGELOG.md
packages/react-article-components/src/components/body/image-diff.js
packages/react-article-components/src/components/leading/fullscreen.js
packages/react-article-components/src/components/leading/normal.js

Fix several style problems

---

packages/react-article-components/src/components/article-page.js
packages/react-article-components/src/components/related/card.js
packages/react-article-components/src/components/related/index.js
packages/react-article-components/src/components/related/list.js
packages/react-article-components/src/constants/prop-types/related.js

https://kanbanflow.com/task-attachment/XkYlkn1ROVTA
https://kanbanflow.com/t/LDJmYY7c

implement related:card on-hover animation

---

packages/react-article-components/CHANGELOG.md
packages/react-article-components/dev/mock-post.json
packages/react-article-components/package.json
packages/react-article-components/src/components/body/index.js
packages/react-article-components/src/components/img-with-placeholder/index.js
packages/react-article-components/src/constants/element-alignment.js
packages/react-article-components/src/constants/prop-types/body.js

Update image components of `react-article-components`

---

packages/react-article-components/CHANGELOG.md
packages/react-article-components/src/components/body/headings.js

Kanban Flow task: https://kanbanflow.com/t/yxvypr2Z

[react-article-components] Fix heading content

---

dev/constants.js
dev/dependencies.test.js
dev/print-dep-intersections.js
dev/utils.js
makefile
package.json
yarn.lock

Kanbanflow card:
[Add Jest test to ensure the shared dependencies will not cause duplicate dependencies be installed](https://kanbanflow.com/t/hhBgp47P)

Add dependencies checking and git pre-push hook

---

packages/react-article-components/CHANGELOG.md
packages/react-article-components/package.json
packages/react-article-components/src/components/body/slideshow/index.js

https://kanbanflow.com/t/q9SfBspy

[react-article-components] prevent image flash while sliding between first and last slide

---

packages/react-article-components/CHANGELOG.md
packages/react-article-components/package.json
packages/react-article-components/src/components/body/blockquote.js
packages/react-article-components/src/components/body/index.js
packages/react-article-components/src/components/body/infobox.js
packages/react-article-components/src/components/body/list.js
packages/react-article-components/src/components/body/multimedia.js
packages/react-article-components/src/components/body/slideshow/index.js
packages/react-article-components/src/managers/theme-manager.js

- [列點功能下，超連結顏色會變成藍色，而非知性土](https://kanbanflow.com/t/EF2YPxmd)
- [在攝影版上使用 table of contents，會出現 error 500](https://kanbanflow.com/t/E7Zzx6PM)
- [infobox內文本來有enter分段，轉換成新版型後全數消失](https://kanbanflow.com/t/EF7K7wAp)
- [攝影版部分，放在引用內的連結會變深藍色，但攝影版的背景也是黑的，就看不見](https://kanbanflow.com/t/E94pkdvv)
- [圖說在攝影頁（手機版）會出現白底白字](https://kanbanflow.com/t/EHCxaw7G)
- [當編輯連續擺放多張圖片，圖說會跟下一張圖片重疊](https://kanbanflow.com/t/ERmNdC1X)

style fine tune and bug fix

---

packages/react-article-components/CHANGELOG.md
packages/react-article-components/dev/mock-post.json
packages/react-article-components/package.json
packages/react-article-components/src/components/article-page.js
packages/react-article-components/src/components/body/embedded-code.js

KanbanFlow task: https://kanbanflow.com/t/w77swM2R

[react-article-components] Fix embedded overflow problem

---

packages/react-article-components/src/components/article-page.js

https://kanbanflow.com/t/2GqpUUgZ

[react-article-components] related block: render null if posts.length === 0

---

packages/react-article-components/CHANGELOG.md
packages/react-article-components/src/components/aside/metadata.js

https://kanbanflow.com/t/4BH66Eo5

[react-article-components] author names without word breaks

---

packages/react-article-components/CHANGELOG.md
packages/react-article-components/src/components/body/index.js
packages/react-article-components/src/components/body/multimedia.js

https://kanbanflow.com/t/RJVA6Xi5
https://kanbanflow.com/t/4dTmfHaL

[react-article-components] multimedia.block style update

---

packages/react-article-components/CHANGELOG.md
packages/react-article-components/src/components/body/index.js

https://kanbanflow.com/t/fnAe22Jm

[react-article-components] fix block is covered by align right block

---

packages/react-article-components/CHANGELOG.md
packages/react-article-components/src/components/article-page.js
packages/react-article-components/src/components/body/slideshow/index.js
packages/react-article-components/src/managers/theme-manager.js

https://kanbanflow.com/t/2Wh1j1Q2

[react-article-components] slideshow: adjust styles in photo theme 

---

packages/react-article-components/CHANGELOG.md
packages/react-article-components/src/components/body/audio/control-button.js
packages/react-article-components/src/components/body/audio/index.js
packages/react-article-components/src/components/body/audio/seek-bar.js

This PR is after https://github.com/twreporter/twreporter-npm-packages/pull/42.
https://kanbanflow.com/t/2ieEpdCW

[react-article-components] audio style tune

---

packages/react-article-components/src/components/article-page.js
packages/react-article-components/src/components/aside/metadata.js
packages/react-article-components/src/components/body/annotation.js
packages/react-article-components/src/components/body/audio/control-button.js
packages/react-article-components/src/components/body/audio/index.js
packages/react-article-components/src/components/body/audio/seek-bar.js
packages/react-article-components/src/components/body/blockquote.js
packages/react-article-components/src/components/body/brief.js
packages/react-article-components/src/components/body/centered-quote.js
packages/react-article-components/src/components/body/embedded-code.js
packages/react-article-components/src/components/body/headings.js
packages/react-article-components/src/components/body/image-diff.js
packages/react-article-components/src/components/body/infobox.js
packages/react-article-components/src/components/body/multimedia.js
packages/react-article-components/src/components/body/paragraph.js
packages/react-article-components/src/components/body/slideshow/index.js
packages/react-article-components/src/components/donation-box.js
packages/react-article-components/src/components/leading/normal.js
packages/react-article-components/src/components/license.js
packages/react-article-components/src/components/related/card.js
packages/react-article-components/src/components/related/index.js
packages/react-article-components/src/components/related/list.js
packages/react-article-components/src/components/separation-curve.js
packages/react-article-components/src/constants/css.js

https://kanbanflow.com/t/zX1aLAS3
Zeplin tags:
`article@2.0.2(FineTune)`
`article@2.1.2(FineTune)`

[react-article-components] style fine tune

---

packages/react-article-components/CHANGELOG.md
packages/react-article-components/dev/entry.js
packages/react-article-components/package.json
packages/react-article-components/src/components/img-with-placeholder/index.js
packages/react-article-components/src/components/related/card.js
packages/react-article-components/src/components/related/index.js
packages/react-article-components/src/components/related/list.js
packages/react-article-components/src/components/related/mockup.js

KanbanFlow task: https://kanbanflow.com/t/zWWBLo1j
Design: https://kanbanflow.com/t/E46FLGmc
> 此版本主要調整以下三部分：
> ① 新增「載入更多」按鈕
> ② Hover「載入更多」按鈕的樣式
> ③ 正在載入時卡片的照片樣式

[react-article-components] Add load-more and update relateds styles

---

packages/react-article-components/CHANGELOG.md
packages/react-article-components/package.json
packages/react-article-components/src/components/body/embedded-code.js
packages/react-article-components/src/components/body/index.js

https://kanbanflow.com/t/MGR61aPR
`article@2.1.5(Embed)`

[react-article-components] embed: style fine tune

---

packages/redux/CHANGELOG.md
packages/redux/package.json
packages/redux/src/constants/post-styles.js

KanbanFlow task: https://kanbanflow.com/t/2g9Cj2yF

[redux] Update photo article style constant to v2

---

packages/react-article-components/CHANGELOG.md
packages/react-article-components/package.json
packages/react-article-components/src/components/body/embedded-code.js

[react-article-components] Fix bugs and release v1.0.25-beta.4

---

packages/react-article-components/CHANGELOG.md
packages/react-article-components/package.json
packages/react-components/CHANGELOG.md
packages/react-components/package.json
packages/react-components/src/bookmark-widget/index.js
packages/universal-header/CHANGELOG.md
packages/universal-header/package.json

Fix ssr error [reported](https://console.cloud.google.com/errors/COC0tPq_4re0hAE?time=PT6H&project=coastal-run-106202&authuser=0) by Stackdriver

fix: [react-components] bookmark-widget error on ssr

---

packages/react-article-components/CHANGELOG.md
packages/react-article-components/package.json
packages/react-components/CHANGELOG.md
packages/react-components/package.json
packages/redux/CHANGELOG.md
packages/redux/package.json
packages/universal-header/CHANGELOG.md
packages/universal-header/package.json

- @twreporter/react-article-components@1.0.27
- @twreporter/react-components@8.0.4
- @twreporter/redux@5.0.8
- @twreporter/universal-header@2.1.3

chore(release): bump version

---

package.json
packages/react-article-components/CHANGELOG.md
packages/react-article-components/package.json
packages/react-article-components/src/components/donation-box.js
packages/react-components/CHANGELOG.md
packages/react-components/package.json
packages/react-components/src/footer/content.js

https://kanbanflow.com/t/gss1FQhG

feat: add annual report link to footer and article page

---

packages/core/src/constants/categories.js
packages/index-page/src/index.js

chore: add void comment messages for ci testing

---

packages/react-components/src/listing-page/components/list.js
packages/redux/src/reducers/__test__/posts.test.js
packages/redux/src/reducers/posts.js

- fix(redux): fix mutating state in posts reducer
- feat(react-components): update list component: only wrap items with isFetching, do not include the header
https://kanbanflow.com/t/KW1U4dnY

Fix listing data reducer and update list component

---

packages/react-article-components/src/components/related/list.js

fix loadmore btn displaying logic.
not to show the btn when the amount of items under first show limit.
https://kanbanflow.com/t/KW1U4dnY

fix(react-article-components): update loadmore btn

---

packages/react-article-components/src/components/body/audio/audio-provider.js

https://kanbanflow.com/t/KW1U4dnY
Howler.js should run on client only, not on server. (https://github.com/goldfire/howler.js#browser-compatibility)

fix: only new audio instance on client

---

.circleci/config.yml
packages/core/CHANGELOG.md
packages/core/package.json
packages/core/src/utils/sign-in-href.js
packages/core/src/utils/sign-out-href.js
packages/index-page/CHANGELOG.md
packages/index-page/package.json
packages/react-article-components/CHANGELOG.md
packages/react-article-components/package.json
packages/react-components/CHANGELOG.md
packages/react-components/package.json
packages/universal-header/CHANGELOG.md
packages/universal-header/package.json

- @twreporter/core@1.2.0-rc.0
- @twreporter/index-page@1.0.8-rc.0
- @twreporter/react-article-components@1.1.4-rc.0
- @twreporter/react-components@8.2.1-rc.0
- @twreporter/universal-header@2.1.6-rc.0

relase packages

---

packages/errors/CHANGELOG.md
packages/errors/README.md
packages/errors/custom-babel-jest.js
packages/errors/jest.config.js
packages/errors/makefile
packages/errors/package.json
packages/errors/src/annotating-error.js
packages/errors/src/helpers/annotate-axios-error.js
packages/errors/src/helpers/general.js
packages/errors/src/helpers/print.js
packages/errors/src/index.js
yarn.lock

Add custom errors to save the stack of errors. So we can add debug information when passing out the internal error.

feat(errors): add new package errors

---

.circleci/config.yml
README.md

chore(circleci): add new package deps cahce

---

packages/react-article-components/CHANGELOG.md
packages/react-article-components/package.json
packages/react-article-components/src/components/body/embedded-code.js

- @twreporter/react-article-components

chore: release

---

packages/react-components/src/listing-page/components/image.js
packages/react-components/src/listing-page/components/list.js
packages/react-components/src/listing-page/components/topics/index.js

- render loading spinner on demand
- replace google cloud storage url origin

refactor(react-components): update listing-page components

---

packages/redux/src/actions/index-page.js
packages/redux/src/actions/posts.js
packages/redux/src/actions/topics.js
packages/redux/src/constants/api-config.js

including
- fetchIndexPageContent
- fetchAFullPost
- fetchPostsByCategoryListId
- fetchPostsByTagListId
- fetchRelatedPostsOfAnEntity
- fetchFeatureTopic
- fetchTopics
- fetchAFullTopic

refactor(redux): add timeout argument for actions

---

packages/redux/src/actions/__test__/author-articles.test.js
packages/redux/src/actions/__test__/author-details.test.js
packages/redux/src/actions/__test__/authors.test.js
packages/redux/src/actions/__test__/mocks/author-articles.js
packages/redux/src/actions/__test__/mocks/authors.js
packages/redux/src/actions/author-articles.js
packages/redux/src/actions/author-details.js
packages/redux/src/actions/authors.js
packages/redux/src/constants/api-endpoints.js
packages/redux/src/constants/authors-list.js
packages/redux/src/reducers/__test__/entities-for-authors.test.js
packages/redux/src/reducers/__test__/mocks/author-articles.js
packages/redux/src/reducers/__test__/mocks/authors.js
packages/redux/src/reducers/__test__/mocks/entities-for-authors.js
packages/redux/src/reducers/author-articles.js
packages/redux/src/reducers/entities-for-authors.js
packages/redux/src/reducers/index.js
packages/redux/src/typedef.js

refactor(redux): updates for authors

---

packages/react-article-components/CHANGELOG.md
packages/react-article-components/package.json

This patch updates CHANGELOG.md to include version 1.2.14.
Also, update version to v1.2.15-rc.0 since v1.2.14 has been released.

chore(react-article-components): update CHANGELOG.md

---

packages/react-components/src/side-bar/index.js

This patch adds a more declarative way to configure side bar.
That is, directly declare the anchors in JSX.

refactor(react-components): update side bar

---

packages/universal-header/package.json

- for the first time included dependency, we should update package.json manualy
- lerna will take further updates

chore(universal-header): add dependency @twreporter/react-component

---

package.json
packages/universal-header/src/components/action-button.js
packages/universal-header/src/components/channels.js
packages/universal-header/src/components/drop-down-menu.js
packages/universal-header/src/components/hamburger-icons.js
packages/universal-header/src/components/hamburger-menu.js
packages/universal-header/src/components/header.js
packages/universal-header/src/components/icons.js
packages/universal-header/src/components/mobile-header.js
packages/universal-header/src/components/slogan.js
packages/universal-header/src/constants/actions.js
packages/universal-header/src/containers/header.js
packages/universal-header/src/utils/animations.js
packages/universal-header/src/utils/theme.js
yarn.lock

feat(universal-header): add narrow type header & header transform animation
- add { toUseHeader, hideHeader } in container/header context
- add utils/animation.js to handle animation keyframe
- handle animation use CSSTransitionGroup

feat(universal-header): add narrow type header & header animation

---

packages/universal-header/src/containers/header.js

- 'isTransforming' typo
- assign variables to null on componentWillUnmount hook
- remove 'mergeTwoArraysInOrder' which is defined but never used

fix: address review comment & lint error

---

packages/react-components/src/footer/content.js
packages/react-components/src/mobile-pop-up-modal.js
packages/universal-header/src/components/action-button.js
packages/universal-header/src/components/channels.js
packages/universal-header/src/components/header.js
packages/universal-header/src/components/slogan.js
packages/universal-header/src/constants/fonts.js
packages/universal-header/src/containers/header.js

- react-components: fix mobile pop up modal position & eslint error
- universal-header: fix style & channel active logic

fix: fix ui defect

---

packages/universal-header/src/components/drop-down-menu.js
packages/universal-header/src/components/header.js
packages/universal-header/src/components/mobile-header.js
packages/universal-header/src/utils/theme.js

- icons border color
- z-index management in Header component
- channel dropdown menu font weight & height

fix(universal-header): fix ui defect

---

packages/core/src/constants/external-links.js
packages/react-components/src/footer/constants/icons.js
packages/react-components/src/footer/icon-list.js

[TWREPORTER-88](https://twreporter-org.atlassian.net/browse/TWREPORTER-88)
- @twreporter/core: add twitter link
- @twreporter/react-components: add twitter & remove line in footer icon list

feat(react-components, core): add twitter entry in footer icon list

---

packages/react-components/src/footer/content.js

- add twreporter lab (medium)
- add brand design (gitlab)
- sort content with category

feat(react-components): rebranding footer

---

packages/core/src/constants/color.js
packages/universal-header/src/components/action-button.js
packages/universal-header/src/components/channels.js
packages/universal-header/src/components/drop-down-menu.js
packages/universal-header/src/components/search-box.js
packages/universal-header/src/components/slogan.js
packages/universal-header/src/constants/colors.js
packages/universal-header/src/utils/theme.js

- follow [design guidline](https://twreporter.gitbook.io/the-reporter-brand-guidelines)

refactor: manage colors in @twreporter/core constants

---

packages/core/src/constants/fundraising.js
packages/react-components/src/footer/index.js

story: [TWREPORTER-196](https://twreporter-org.atlassian.net/browse/TWREPORTER-196)
- add core constants/fundraising.js: store fund-raising number
- fund-raising number will update every year
- add fund-raising number in footer

feat(core, react-components): add fund-raising number

---

README.md

This patch add test guide in README.md.

docs: add test guide to README.md

---

packages/react-article-components/package.json

bump version to test npm auth(2FA issue) for CI

chore: bump version

---

packages/react-components/src/bookmark-list/bookmark.js
packages/react-components/src/bookmark-list/bookmarks.js
packages/react-components/src/bookmark-list/empty-guide.js
packages/react-components/src/button/utils/theme.js

- use old bookmark add icon
- fix bookmark style
- fix pill button style

fix: fix defect & pill button style

---

packages/react-components/src/button/components/iconButton.js
packages/react-components/src/button/components/iconWithTextButton.js
packages/react-components/src/button/index.js
packages/react-components/src/button/stories/iconButton.stories.js
packages/react-components/src/button/stories/iconWithTextButton.stories.js
packages/react-components/src/button/utils/theme.js
packages/react-components/src/icon/index.js
packages/react-components/src/icon/stories/printer.stories.js

- button
- IconButton
- IconWithTextButton
- icon
- Printer

feat: add IconButton, IconWithTextButton, Printer components

---

packages/react-components/src/bookmark-list/index.js

- [TWREPORTER-182](https://twreporter-org.atlassian.net/browse/TWREPORTER-182): fetch new bookmarks when component mount

fix: bookmark should fetch upstream when page mount

---

packages/react-components/src/bookmark-list/index.js
packages/redux/src/reducers/bookmarks.js

- related issue: [TWREPORTER-182](https://twreporter-org.atlassian.net/browse/TWREPORTER-182)

fix: new bookmark should be fetched when mount

---

.eslintrc
package.json
packages/react-article-components/package.json
packages/react-article-components/src/components/article-page.js
packages/react-article-components/src/components/aside/mobile-tool-bar.js
packages/react-components/src/hook/index.js
packages/react-components/src/hook/use-outside-click.js
packages/react-components/src/icon/index.js
yarn.lock

- add `react-scroll` package for smooth scroll
- add snackbar for bookmark action ([TWREPORTER-375](https://twreporter-org.atlassian.net/browse/TWREPORTER-375))
- fix desktop tools not work ([TWREPORTER-376](https://twreporter-org.atlassian.net/browse/TWREPORTER-376))
- fix back top topic wording ([TWREPORTER-385](https://twreporter-org.atlassian.net/browse/TWREPORTER-385))

fix: fix tool bar defect

---

packages/react-article-components/src/components/body/embedded-code.js

Reverts twreporter/twreporter-npm-packages#286

Revert "Jason/issue 60"

---

packages/index-page/src/components/junior-box-section.js
packages/index-page/src/index.js
packages/react-components/src/junior-link.js

Address [TWREPORTER-412](https://twreporter-org.atlassian.net/browse/TWREPORTER-412)

Add banner for the reporter junior

---

packages/react-components/src/listing-page/components/list.js
packages/react-components/src/title-bar/components/bar.js
packages/react-components/src/title-bar/components/tab.js
packages/redux/src/actions/__test__/posts.test.js
packages/redux/src/actions/index.js
packages/redux/src/actions/posts.js

- [TWREPORTER-381](https://twreporter-org.atlassian.net/browse/TWREPORTER-381)

[feat] add `fetchPostsByCategorySetListId` action

---

packages/index-page/src/components/category-section.js
packages/index-page/src/components/common-utils/mobile-list.js
packages/index-page/src/components/common-utils/section-content-wrapper.js
packages/index-page/src/components/common-utils/section-name.js
packages/index-page/src/components/common-utils/section.js
packages/index-page/src/components/donation-box-section.js
packages/index-page/src/components/editor-picks.js
packages/index-page/src/components/infographic-section.js
packages/index-page/src/components/junior-box-section.js
packages/index-page/src/components/latest-section.js
packages/index-page/src/components/latest-topic.js
packages/index-page/src/components/mobile-flex-swipeable.js
packages/index-page/src/components/news-letter-section.js
packages/index-page/src/components/photography-section.js
packages/index-page/src/components/podcast-box-section.js
packages/index-page/src/components/reviews.js
packages/index-page/src/components/topics-section.js
packages/index-page/src/utils/style-utils.js

- [TWREPORTER-383](https://twreporter-org.atlassian.net/browse/TWREPORTER-383)
- replace local media query with @twreporter/core mq
- adjust index-page latest section animation time & card style

fix: index-page style & animation

---

packages/react-article-components/src/components/aside/mobile-tool-bar.js
packages/react-components/src/button/components/pillButton.js
packages/react-components/src/snack-bar/hooks/use-snack-bar.js
packages/react-components/src/snack-bar/index.js
packages/react-components/src/snack-bar/stories/snackBar.stories.js

- react-components
- add useSnackBar hook (headless UI !!)
- add useSnackBar story
- react-article-components
- apply useSnackBar hook

[enhancement] add `useSnackBar` hook

---

packages/index-page/src/components/common-utils/img-wrapper.js
packages/index-page/src/components/editor-picks.js
packages/react-article-components/src/components/img-with-placeholder/index.js
packages/react-article-components/src/components/leading/fullscreen.js
packages/react-article-components/src/components/leading/normal.js
packages/react-article-components/src/components/leading/pink.js

Address [TWREPORTER-426](https://twreporter-org.atlassian.net/browse/TWREPORTER-426)

Adopt browser-level image lazy-loading

---

packages/index-page/src/components/junior-box-section.js
packages/react-components/src/junior-link.js

- story: https://app.asana.com/0/1202896150264815/1203223305893191/f

fix: update kids reporter link & wording

---

packages/core/src/constants/category-set.js
packages/react-components/src/button/components/textButton.js
packages/react-components/src/input/components/search-bar.js
packages/react-components/src/title-bar/components/tab.js
packages/universal-header/src/components/channels.js
packages/universal-header/src/components/hamburger-menu.js
packages/universal-header/src/components/header.js
packages/universal-header/src/components/icons.js
packages/universal-header/src/components/slogan.js
packages/universal-header/src/utils/links.js

- This patch address defects in [header story](https://app.asana.com/0/1202896150264815/1202942985879108/f) & [category story](https://app.asana.com/0/1202896150264815/1202904767639024/f)
- fix header style
- fix tab bar style
- use TextButton in TabBar component
- close hamburger menu when click logo
- unmount logout dialog after hiding animation
- fix login/out url
- open about us page in new tab

fix: address defects

---

packages/index-page/src/components/junior-box-section.js
packages/index-page/src/components/podcast-box-section.js
packages/index-page/src/constants/app.js

fix https://app.asana.com/0/1202896150264815/1203309142649553/f
companion PR: https://github.com/twreporter/twreporter-react/pull/2299

fix: update kids banner

---

packages/react-components/src/input/components/search-bar.js
packages/react-components/src/input/constants/type.js
packages/react-components/src/input/stories/search-bar.stories.js
packages/react-components/src/rwd.js
packages/universal-header/src/components/action-button-item.js
packages/universal-header/src/components/action-button-item.stories.js
packages/universal-header/src/components/action-button.js
packages/universal-header/src/components/hamburger-menu.js
packages/universal-header/src/components/header.js
packages/universal-header/src/components/header.stories.js
packages/universal-header/src/components/icons.js
packages/universal-header/src/components/slogan.js
packages/universal-header/src/components/tab-bar.js
packages/universal-header/src/components/tab-bar.stories.js
packages/universal-header/src/constants/action-item-types.js
packages/universal-header/src/constants/actions.js
packages/universal-header/src/constants/channels.js
packages/universal-header/src/constants/prop-types.js
packages/universal-header/src/containers/header.js
packages/universal-header/src/utils/links.js
packages/universal-header/src/utils/theme-old.js
packages/universal-header/src/utils/theme.js

- react-components
- add rwd releated components
- universal-header
- add TabBar component
- rename action-button.js to action-button-item.js
- add action-button.js for rwd interface
- add HamburgerContext to share hamburger related states
- fix Slogan font-family

feat: add mobile & tablet view for new info structure

---

packages/universal-header/src/components/hamburger-menu-item.js
packages/universal-header/src/utils/theme.js

- a:visited, a:link color is assigned global in membership-fe

fix: fix text color in a tag

---

packages/react-article-components/src/components/article-page.js
packages/react-article-components/src/components/aside/metadata.js
packages/react-article-components/src/components/body/index.js
packages/react-article-components/src/components/leading/normal.js
packages/react-components/src/bookmark-list/bookmarks.js
packages/react-components/src/listing-page/components/list.js
packages/react-components/src/listing-page/components/topics/index.js
packages/react-components/src/listing-page/components/topics/page-content.js
packages/react-components/src/listing-page/components/topics/section.js

Reverts twreporter/twreporter-npm-packages#327

Revert "Jason/refinement new arch"

---

packages/react-article-components/src/components/article-page.js
packages/react-article-components/src/components/aside/metadata.js
packages/react-article-components/src/components/body/index.js
packages/react-article-components/src/components/leading/normal.js
packages/react-components/src/bookmark-list/bookmarks.js
packages/react-components/src/listing-page/components/list-item.js
packages/react-components/src/listing-page/components/list.js
packages/react-components/src/listing-page/components/page-content.js
packages/react-components/src/listing-page/components/topics/index.js
packages/react-components/src/listing-page/components/topics/section.js
packages/react-components/src/listing-page/constants/mockup-spec.js
packages/react-components/src/title-bar/components/bar.js

This reverts commit d17ff3b7133534b23498f3ca5a7b5f30988ee8ca.
fix https://app.asana.com/0/1202896150264815/1202959962459839
companion PR: https://github.com/twreporter/twreporter-react/pull/2317

Revert "Revert "Jason/refinement new arch""

---

packages/react-components/src/card/components/dialog.js
packages/universal-header/src/components/hamburger-footer.js
packages/universal-header/src/components/hamburger-menu.js
packages/universal-header/src/components/header.js
packages/universal-header/src/components/icons.js
packages/universal-header/src/components/tab-bar.js
packages/universal-header/src/constants/prop-types.js
packages/universal-header/src/containers/header.js

This patch fix defect for mobile universal-header listing in [story](https://app.asana.com/0/1202896150264815/1202942985879116/f).
- add referrer location props (which would be passed from react-router-dom (refer to [twreporter-react #2323](https://github.com/twreporter/twreporter-react/pull/2323)))
- fix styles in header & hamburger menu
- fix styles with ios safe area

fix: fix defects

---

packages/react-components/src/listing-page/components/page-content.js

fix: fix width

---

packages/core/src/constants/fundraising.js

This patch update fundraising number to 2023 version.

fix: update 2023 fundraising id

---

packages/redux/src/actions/index.js
packages/redux/src/actions/latest.js
packages/redux/src/actions/posts.js
packages/redux/src/constants/action-types.js
packages/redux/src/constants/api-endpoints.js
packages/redux/src/constants/redux-state-field-names.js
packages/redux/src/reducers/index.js
packages/redux/src/reducers/latest.js

This patch add action & reducer for latest page's redux state management.

feat: add latest page action & reducer

---

packages/core/src/constants/feature-flag.js
packages/index-page/src/components/category-section.js
packages/redux/src/actions/posts.js
packages/redux/src/constants/latest.js
packages/redux/src/index.js

- reudx
- export `LATEST_LIST_ID` constants
- index-page
- fix react warning when same article occur in different category

fix: address review comment

---

packages/react-article-components/src/components/article-page.js

fix field rename issue to avoid block testing, storybook will be another PR

fix: fix rename issue

---

packages/universal-header/src/utils/links.js

- This patch add missing import to fix js error

fix: add missing import

---

packages/universal-header/src/components/channels.js
packages/universal-header/src/components/hamburger-menu.js
packages/universal-header/src/constants/channels.js
packages/universal-header/src/utils/links.js

This patch fix defect [[defect] header 未顯示「最新」、「深度專題」兩個項目](https://app.asana.com/0/1203699264568808/1203964076256284/f)

fix: patch latest & topic on desktop channel

---

packages/react-components/src/card/components/article-card.js
packages/react-components/src/listing-page/components/card-list.js
packages/react-components/src/listing-page/stories/cardList.stories.js

defects in `[[defect] 最新頁的 UI 應該是 list，而不是 grid](https://app.asana.com/0/1203699264568808/1203983432530623/f)`

fix: article card list style

---

packages/react-components/src/listing-page/components/card-list.js

fix `hd` & `tablet` cannot show list

fix: card list rwd

---

packages/react-components/src/material-icon.js
packages/universal-header/src/components/tab-bar.js

`Unexpected syntax : @font-face` error when twreporter-react `make dev`
The main reason is that [@font-face](https://www.w3schools.com/cssref/css3_pr_font-face_rule.php) should be imported on root file.
N/A

fix: @font-face should use in root file

---

packages/index-page/src/components/latest-section.js
packages/react-components/src/listing-page/components/card-list.js
packages/react-components/src/listing-page/components/page-content.js

[[defect] 分類頁 / tag 頁跑版](https://app.asana.com/0/0/1204547368582862/f)
N/A

fix: listing-page style

---

packages/react-components/src/empty-state/index.js

change image width by Style
[[defect] 圖片寬度：pencil width= 232px、under_construction width=177px](https://app.asana.com/0/0/1204549060438489/f)

fix: change image width

---

packages/universal-header/src/components/header.js
packages/universal-header/src/containers/header.js

[[維運] tab bar swipe up/down  互動效果不穩定](https://app.asana.com/0/1202936421725081/1204562785673206/f)
twreporter-react [#2474](https://github.com/twreporter/twreporter-react/pull/2474)

fix: not apply position: fixed on tab bar

---

packages/index-page/src/components/latest-section.js

[[維運] 首頁置頂最新文章區塊的分類顯示邏輯](https://app.asana.com/0/1202936421725081/1204556987381312/f)
N/A

fix: latest section category field wording

---

packages/universal-header/src/components/header.js

hamburger menu should be on top
N/A

fix: remove redundent z-index

---

packages/core/src/constants/member-role.js
packages/react-components/.storybook/preview.js
packages/react-components/src/mobile-member-role-card/index.js
packages/react-components/src/mobile-member-role-card/stories/member-role-card.stories.js

[[會員制] 會員專區的 mobile 會員卡元件](https://app.asana.com/0/1203699264568808/1204568767509308/f)

feat: mobile member role card

---

packages/react-components/src/mobile-member-role-card/index.js

fix picture height calculate problem

fix: use flex for auto fill

---

packages/core/src/constants/release-branch.js
packages/core/src/constants/request-origins.js

chore: add dev branch request

---

packages/react-components/src/empty-state/index.js

[[會員制] 贊助紀錄頁](https://app.asana.com/0/1203699264568808/1204692921007276/f) defect

fix: fix empty state margin

---

packages/react-components/src/simple-header/index.js

fix: simple-header style

---

packages/react-components/src/input/components/text-field.js

[[會員制] 登入註冊：OTP delay 的 UI 調整](https://app.asana.com/0/1203699264568808/1204692921007280/f)

fix: remove input border radius

---

packages/universal-header/src/components/hamburger-menu.js
packages/universal-header/src/components/icons.js

fix: add isForHambuger prop for MobileIcons

---

packages/core/src/constants/feature-flag.js
packages/universal-header/src/components/action-button-item-old.js
packages/universal-header/src/components/action-button.js
packages/universal-header/src/components/hamburger-menu-old.js
packages/universal-header/src/components/header-old.js
packages/universal-header/src/components/icons-old.js
packages/universal-header/src/constants/external-links.js
packages/universal-header/src/constants/services-old.js
packages/universal-header/src/containers/header.js
packages/universal-header/src/utils/links-old.js

[[會員制] 全域導覽 URL 變更](https://app.asana.com/0/1203699264568808/1204830463458311/f)
- MEMBERSHIP true
- link `newsletter` to `account` page
- logout in `account` page
- MEMBERSHIP false (before `account` page ready)
- link `newsletter` to `mailchimp`
- logout in header `member` icon
N/A

feat: add MEMBERSHIP feature flag

---

packages/core/src/constants/feature-flag.js

[[會員制] 全域導覽 URL 變更](https://app.asana.com/0/1203699264568808/1204830463458311/f)

chore: enable MEMBERSHIP toggle for testing

---

packages/core/src/constants/font.js

[[維運] 換歐文字體：Rosario → Roboto Slab](https://app.asana.com/0/1203699264568808/1204021261528991/f)

chore: use Roboto Slab font

---

packages/core/src/constants/entity-path.js
packages/react-components/src/footer/content.js

[[會員制] footer 訂閱電子報連結](https://app.asana.com/0/1203699264568808/1205156951419958/f)
[[維運] 主網站 footer 的品牌規範 [new] badge 拿掉](https://app.asana.com/0/1203699264568808/1204054870701167/f)

fix: footer email link and remove new tag

---

packages/universal-header/src/components/header.js

feat: check if is at account page

---

packages/react-components/src/mobile-member-role-card/index.js

[[個人專區] 名字、email 太長時會破版](https://app.asana.com/0/0/1205245838889275/f)
- desktop issue fix in twreporter-react [#2595](https://github.com/twreporter/twreporter-react/pull/2595)
N/A

fix: wrap member role card text when overflow

---

packages/react-components/src/empty-state/index.js

fix: text align center

---

packages/universal-header/src/components/header.js
packages/universal-header/src/containers/header.js

[[spec change] 在 menu 開啟的時候，不要跳 popup
](https://app.asana.com/0/0/1205148796963909/f)
N/A

fix: add `hamburgerContext` props

---

packages/redux/src/actions/index.js
packages/redux/src/actions/user.js
packages/redux/src/constants/api-endpoints.js

[[維運] onboarding 完，沒辦法維持登入狀態](https://app.asana.com/0/1203699264568808/1205329976326260/f)
- test case would be updated in next PR
go-api [#590](https://github.com/twreporter/go-api/pull/590)

fix: add `onboarding` action

---

packages/react-components/src/button/components/link.js
packages/react-components/src/button/stories/link.stories.js

[[會員制] OTP 前端](https://app.asana.com/0/1203699264568808/1205274424080442/f)
N/A

feat: add disabled style for LinkButton

---

packages/universal-header/src/components/icons.js

[[維運] header search bar 的點擊效果](https://app.asana.com/0/1203699264568808/1205274424985723/f)

fix: remove close on blur

---

babel.config.js
package.json
yarn.lock

chore: add css modules transform for babel

---

packages/index-page/src/components/editor-picks-mobile.js

add key `editor-pick-mobile` item

fix: add key

---

packages/index-page/src/components/editor-picks-mobile.js

[[維運] 首頁卡片滑動效果](https://app.asana.com/0/1203699264568808/1205274424985703/f) defects

fix: swiper text and image together

---

packages/index-page/src/components/category-section.js

[[defect] 議題區塊的「更多＿＿＿＿>」不見了](https://app.asana.com/0/0/1205517195405683/f)

fix: index page more link

---

packages/universal-header/src/components/icons.js

[[維運] header search bar 的點擊效果](https://app.asana.com/0/1203699264568808/1205274424985723/f)

fix: universal header close search bar while search

---

packages/core/src/constants/donation-link-anchor.js
packages/react-article-components/src/components/donation-box.js

[[會員制] 站內導流至贊助頁變更錨點位置](https://app.asana.com/0/1203699264568808/1205495810236174/f)

feat: add donation anchor & change link

---

packages/react-components/src/button/components/pillButton.js
packages/react-components/src/button/stories/pillButton.stories.js

[[spec change] btn loading state](https://app.asana.com/0/0/1205646853643264/f)
N/A

feat: add `loading` props for PillButton

---

packages/react-components/src/button/components/pillButton.js

style broken when left/right icon added in pillbutton
N/A

fix: pillbutton layout with icons

---

packages/react-article-components/src/components/article-page.js
packages/react-article-components/src/components/body/index.js
packages/react-article-components/src/components/table-of-contents/index.js

[[會員制] 文章頁 bottom banner](https://app.asana.com/0/1203699264568808/1205329976610294/f)

feat: emit onToggleTabExpanded

---

packages/react-components/src/button/components/iconButton.js
packages/react-components/src/button/components/iconWithTextButton.js
packages/react-components/src/button/components/pillButton.js
packages/react-components/src/button/components/textButton.js
packages/react-components/src/button/components/toggleButton.js

[[維運] 贊助頁-移除預設選擇「每月定額」](https://app.asana.com/0/1203699264568808/1205832308310327/f)

feat: cursor default while disabled

---

packages/react-components/src/text/paragraph.js

fix `react-components` **_paragraph_** `user agent stylesheet` margin block issue

fix: paragraph margin block

---

packages/react-components/src/button/components/link.js

defects in [[維運] 會員頁-電子報設定新增「少年報導者」](https://app.asana.com/0/1203699264568808/1205728019440902/f)
N/A

fix: `InheritLinkButton` cannot set link & style

---

packages/core/src/constants/reading-time-unit.js
packages/react-components/src/mobile-member-role-card/index.js

[[會員制] 個人閱讀紀錄-會員頁UI更新](https://app.asana.com/0/1203699264568808/1205830825368922/f) defects

fix: mobile role card text style

---

packages/core/src/constants/request-origins.js

[[defect] mobile 從最新頁進入文章，按左上角的返回 icon 會回到首頁，但應該回到最新頁
](https://app.asana.com/0/0/1205948118099046/f)
N/A

fix: request origin typo

---

packages/react-article-components/src/components/related/list.js

[[spec change] gray25 改為 white 0.1 (#FFFFFF1a)](https://app.asana.com/0/1203699264568808/1205754859454996/f)
N/A

fix: update style

---

packages/react-components/src/mobile-member-role-card/index.js

fix: mobile-member-role-card width

---

packages/react-components/src/button/stories/link.stories.js
packages/universal-header/src/components/action-button-item.stories.js

[defects in storybook 支援 node.js v18 (deadline: 2024/02/06)](https://app.asana.com/0/1203699264568808/1205599989492468/f)
N/A

fix: storybook defects

---

packages/core/src/constants/category-set.js

[[資訊架構] 新增「基金會消息」主分類](https://app.asana.com/0/1203699264568808/1204556989907532/f)
N/A

fix: add new added category set ids

---

packages/react-components/src/footer/content.js

[[資訊架構] 新增「基金會消息」主分類](https://app.asana.com/0/1203699264568808/1204556989907532/f)
N/A

fix: link to category page for footer foundation

---

packages/react-article-components/src/components/leading/normal.js

[[維運] 文章頁標題換成 design system](https://app.asana.com/0/1203699264568808/1205893616990834/f) defects

fix: font family and font size for article title

---

packages/core/src/constants/feature-flag.js

disable feature toggle for release

chore: disable feature toggle

---

packages/react-article-components/src/components/body/headings.js

[一些文章出現html語法](https://app.asana.com/0/0/1206211289316587/f)

fix(react-article-components): filter html tag for text render

---

packages/react-article-components/src/components/article-page.js

[[維運]列印時不要出現toolbar](https://app.asana.com/0/1202936421725081/1206147518783230/f)

feat: hide tool bar while print screen

---

packages/core/src/constants/fundraising.js

[[維運] 更新勸募字號、Copyright](https://app.asana.com/0/1202936421725081/1206077554159895/f)
copyright would update by year
N/A

fix: update 2024 fundraising code

---

packages/core/src/constants/color.js

[[defect] 彈窗的背景黑色遮罩不見了](https://app.asana.com/0/0/1206242748694203/f)

fix: add black_0.8 color in design system

---

packages/redux/package.json
yarn.lock

chore: add node-fetch to redux

---

packages/react-components/src/empty-state/index.js

[[贊助流程] 信用卡授權失敗 error message - 前端 / 串接](https://app.asana.com/0/1203699264568808/1206157421685878/f)
N/A

feat: add `buttonOnclick` props for `EmptyState` component

---

packages/redux/src/actions/posts.js

[[會員制] 我的閱讀 - 最新頁新增收藏功能](https://app.asana.com/0/1203699264568808/1206201445527861/f)
https://github.com/twreporter/go-api/pull/657

feat: pass authentication token when getting latest posts

---

packages/react-components/src/hook/use-bookmark.js
packages/redux/src/reducers/entities.js

[[會員制] 我的閱讀 - 最新頁新增收藏功能
](https://app.asana.com/0/1203699264568808/1206201445527861/f)
N/A

fix: update bookmarkId in post entity state & pass bookmark as parameter when create

---

packages/react-components/src/title-bar/components/title2.js
packages/react-components/src/title-bar/stories/title2.stories.js

[[會員制] 我的閱讀 - 新增及修改 design system 元件](https://app.asana.com/0/1203699264568808/1206252112911356/f) spec change

fix: title 2 spec changed

---

packages/core/src/constants/feature-flag.js

close `MY_READING` feature flag for releasing

chore: close MY_READING feature flag

---

packages/react-article-components/src/components/aside/desktop-tools.js
packages/react-article-components/src/components/aside/mobile-tool-bar.js

check `isBookmark` if is not server side render

fix: auto check true

---

packages/redux/src/reducers/entities.js

[[defect] 最新頁會被觸發收藏狀態不正常顯示
](https://app.asana.com/0/0/1206426679139547/f)
N/A

fix: update bookmarkId in post entity after get single bookmark

---

packages/redux/src/reducers/entities.js

[[defect] 最新頁會被觸發收藏狀態不正常顯示
](https://app.asana.com/0/0/1206426679139547/f)
N/A

fix: force update post entity after get post on latest page

---

packages/react-components/src/footer/constants/styles.js
packages/react-components/src/footer/content.js

[[defect] footer 除了 X icon 之外，其他沒改到](https://app.asana.com/0/0/1206608532682607/f)
N/A

fix: footer styles

---

packages/core/src/constants/feature-flag.js

turn off MY_READING feature for releasing

fix: turn off MY_READING feature toggle

---

packages/core/src/constants/member-role.js

The NTCH collaboration roles incorrect
Keep the old role key for fallback compatibility.  Should be remove in the future.

fix: change ntch roles

---

packages/core/CHANGELOG.md
packages/core/package.json
packages/core/src/constants/member-role.js
packages/index-page/CHANGELOG.md
packages/index-page/package.json
packages/react-article-components/CHANGELOG.md
packages/react-article-components/package.json
packages/react-components/CHANGELOG.md
packages/react-components/package.json
packages/redux/CHANGELOG.md
packages/redux/package.json
packages/universal-header/CHANGELOG.md
packages/universal-header/package.json

chore: release 

---

packages/react-components/src/listing-page/components/topics/index.js
packages/react-components/src/listing-page/components/topics/section.js

[[維運] 深度專題 title bar](https://app.asana.com/0/1203699264568808/1206379506612351/f)

style: change topic listing page title components

---

packages/universal-header/src/constants/footer-old.js
packages/universal-header/src/constants/footer.js

fix: import from lib instead of src

---

packages/react-components/src/donation-link.js
packages/react-components/src/footer/content.js
packages/universal-header/src/components/action-button-item.js
packages/universal-header/src/components/action-button.js
packages/universal-header/src/constants/actions.js

[[GA埋碼] 全域導覽事件](https://app.asana.com/0/1203699264568808/1206430327331731/f)
N/A

feat: add element id for gtm

---

packages/redux/src/actions/posts.js

[[defect] 最新頁無正常顯示收藏文章](https://app.asana.com/0/1203699264568808/1206633978405324/f)
https://github.com/twreporter/go-api/pull/681

fix: add `toggleBookmark` parameter for posts action

---

packages/react-article-components/src/components/article-page.js
packages/react-article-components/src/components/aside/mobile-tool-bar-old.js
packages/react-article-components/src/components/aside/mobile-tool-bar.js
packages/react-article-components/src/components/aside/utils/theme.js

[[維運] toolbar 與 header 動畫調整](https://app.asana.com/0/1203699264568808/1206117666290866/f) defects
[[維運] toolbar redesign](https://app.asana.com/0/1203699264568808/1206691242770507/f) defects

fix: share container bg color & scroll throttle

---

packages/react-components/src/pagination/index.js

[[維運] 調整 pagination 樣式](https://app.asana.com/0/1203699264568808/1204114487324885/f)

feat: add mobile pagination

---

packages/react-components/src/pagination/index.js

[[維運] 調整 pagination 樣式](https://app.asana.com/0/1203699264568808/1204114487324885/f) defects

fix: pagination number position center

---

packages/react-components/src/color.stories.js

[[spec change] default showColorText=ture
](https://app.asana.com/0/0/1207095807997119/f)
N/A

fix: set `showColorText` init value `true`

---

packages/core/src/constants/feature-flag.js

[[會員制]個人贊助紀錄 phase2-UI](https://app.asana.com/0/1203699264568808/1207110894426078/f)

feat: add donation history phase 2 feature toggle

---

packages/core/src/constants/feature-flag.js

chore: close feature toggle for release

---

packages/core/src/constants/feature-flag.js

[[會員制]個人贊助紀錄 phase2-前端](https://app.asana.com/0/1203699264568808/1207133511967082/f)

feat: remove donation phase 2 feature toggle

---

packages/react-article-components/src/components/body/slideshow/index.js

[[維運]攝影 slideshow 修改圖像比例](https://app.asana.com/0/1203699264568808/1206979237719148/f)

feat: set aspect-ratio for slideshow

---

packages/core/src/constants/z-index.js

[[維運] 重要公告通知](https://app.asana.com/0/1203699264568808/1207022306464035/f)
N/A

fix: update zIndex constant file

---

packages/react-components/src/footer/constants/links.js
packages/react-components/src/footer/index.js
packages/react-components/src/footer/link.js

[[維運] footer 設計變更](https://app.asana.com/0/1203699264568808/1206827670326360/f) defects

fix: fix defects and add comments

---

packages/index-page/package.json
packages/react-article-components/package.json
packages/react-article-components/src/components/article-page.js
packages/react-article-components/src/components/aside/desktop-aside.js
packages/react-article-components/src/components/aside/desktop-tools.js
packages/react-article-components/src/components/aside/metadata.js
packages/react-article-components/src/components/aside/mobile-tool-bar.js
packages/react-article-components/src/components/body/annotation.js
packages/react-article-components/src/components/body/audio/control-button.js
packages/react-article-components/src/components/body/embedded-code.js
packages/react-article-components/src/components/body/image-diff.js
packages/react-article-components/src/components/body/image.js
packages/react-article-components/src/components/body/multimedia.js
packages/react-article-components/src/components/body/slider/index.js
packages/react-article-components/src/components/body/slideshow/index.js
packages/react-article-components/src/components/img-with-placeholder/index.js
packages/react-article-components/src/components/leading/normal.js
packages/react-article-components/src/components/leading/pink.js
packages/react-article-components/src/components/related/card.js
packages/react-article-components/src/components/related/list.js
packages/react-article-components/src/components/table-of-contents/index.js
packages/react-article-components/src/components/table-of-contents/styled.js
packages/react-components/package.json
packages/react-components/src/icon/index.js
packages/universal-header/src/components/header.js
yarn.lock

fix defects in [[工程] 升級 react 至 v18](https://app.asana.com/0/1203699264568808/1206928795847186/f)
- align `react-waypoint` version with `twreporter-react`
- fix transient props cases
N/A

fix: upgrade `react-waypoint` version

---

packages/react-components/src/button/components/link.js
packages/universal-header/src/components/action-button-item.js

- [[defect] menu btn 樣式錯誤](https://app.asana.com/0/1203699264568808/1207321590496729/f)
- [[defect] 超連結顯示異常](https://app.asana.com/0/1203699264568808/1207320733207642/f)
N/A

fix: missing style $

---

packages/index-page/src/components/editor-picks.js
packages/react-components/src/footer/index.js

[footer顯示異常，首頁、贊助頁/註冊頁的異常狀態不同
](https://app.asana.com/0/1203699264568808/1207321590496716/f)
N/A

fix: footer info link style

---

packages/react-article-components/src/components/img-with-placeholder/index.js

fix: src => lib

---

packages/core/src/utils/media-query.js
packages/react-article-components/src/components/img-with-placeholder/index.js

[[defect] 手機版點擊後會導致無法滑動](https://app.asana.com/0/1203699264568808/1207465762212942/f)

fix: add isMobile condition

---

packages/react-article-components/src/components/aside/mobile-tool-bar.js

[[維運] toolbar sharing bar 隨滑動消失](https://app.asana.com/0/1203699264568808/1206804170068387/f)
N/A

fix: hide share option when hide toolbar

---

packages/react-components/src/footer/constants/links.js

[[維運] footer 超連結對象修改](https://app.asana.com/0/1203699264568808/1207466978658904/f)
N/A

fix: update footer email subscription link

---

packages/react-article-components/src/components/article-page.js
packages/react-article-components/src/components/body/index.js
packages/react-article-components/src/components/body/infobox.js
packages/react-article-components/src/components/body/tracking-section.js

[[會員制]重要報導追蹤-UI/前端: 文章頁](https://app.asana.com/0/1203699264568808/1207085276870883/f)

feat: add tracking section for article components

---

packages/universal-header/src/containers/header.js

[[工程] 升級 react-redux 至 v9](https://app.asana.com/0/1203699264568808/1206928795847188/f) defects

fix(universal-header): fix scroll hide issue

---

packages/react-article-components/src/components/body/image.js
packages/react-article-components/src/components/body/paragraph.js
packages/react-article-components/src/components/body/tracking-section.js

[[會員制]重要報導追蹤-UI/前端: 文章頁](https://app.asana.com/0/1203699264568808/1207085276870883/f) spec changes & defects

feat: prop for tracking section

---

packages/react-components/src/listing-page/components/topics/index.js

[[維運] 深度專題標題字級調整](https://app.asana.com/0/1203699264568808/1207653143848645/f)

feat(react-components): change topic listing page title to H1

---

packages/react-article-components/src/components/body/centered-quote.js

[[維運] 文章頁 quote 文字大小](https://app.asana.com/0/1203699264568808/1207074021625247/f)

feat(react-article-components): centered-quote font size

---

.gitignore
lerna.json
package.json
yarn.lock

chore: upgrade lerna to 6.6.2

---

packages/index-page/CHANGELOG.md
packages/index-page/package.json
packages/react-article-components/CHANGELOG.md
packages/react-article-components/package.json
packages/react-components/CHANGELOG.md
packages/react-components/package.json
packages/redux/CHANGELOG.md
packages/redux/package.json
packages/universal-header/CHANGELOG.md
packages/universal-header/package.json
yarn.lock

chore: update yarn.lock

---

packages/index-page/src/components/topics-section.js
packages/redux/src/reducers/donation-history.js

fix index-page `topics-section` image width issue at desktop
fix redux mutate state warning at dispatch

fix: add flex css for ImgColumn

---

packages/universal-header/src/components/header.js

[[defect] header 隱藏連結仍可被點擊](https://app.asana.com/0/1203699264568808/1207819101456754/f)

fix: disable click while header is narrow

---

packages/react-components/src/footer/constants/links.js
packages/react-components/src/text/utils/webfonts.js

[[維運] 豆腐烏體不串其他字重](https://app.asana.com/0/1203699264568808/1208207898132433/f)
[[維運] footer 新增 公益合作](https://app.asana.com/0/1203699264568808/1208371449012137/f)
N/A

feat: add charity cooperation on footer & fix: add font weight config for each fonts

---

packages/redux/src/actions/receipt.js
packages/redux/src/constants/api-endpoints.js
packages/redux/src/reducers/index.js
packages/redux/src/store/create-store.js

[[電子收據] 個人專區 / 贊助紀錄: 新增下載單筆電子收據](https://app.asana.com/0/1203699264568808/1208291459662974/f)
https://github.com/twreporter/go-api/pull/789

feat: add receipt actions with rtk query

---

packages/react-article-components/src/components/leading/embedded.js

[[維運] embeded 滿版新增 place holder 畫面
](https://app.asana.com/0/1203699264568808/1208371474585818/f)
N/A

fix: add timeout before hide loading

---

packages/react-article-components/src/components/body/embedded-code.js

[[維運] 調整 lazy load 載入資料的時間點
](https://app.asana.com/0/1203699264568808/1208371474585820/f)
N/A

fix: update bottomOffset of embedded waypoint

---

packages/react-components/src/footer/constants/links.js
packages/universal-header/src/constants/external-links.js

[[hotfix] footer/ 改周邊網址](https://app.asana.com/0/1203699264568808/1208793364656377/f)

fix: change merchandise link

---

packages/react-article-components/src/components/body/index.js

[[hotfix] 後續與迴響改文字「後續/迴響」](https://www.notion.so/twreporter/hotfix-15e8dbdca93280489c43d655f63b658b?pvs=4)
N/A

fix: update tracking section title wording

---

packages/core/src/constants/fundraising.js

[[維運] 更新勸募字號、Copyright-2025](https://www.notion.so/twreporter/Copyright-2025-67bdec71d7eb42ef9626cae84d013cd7?pvs=4)
N/A

fix: update fundraising code

---

packages/universal-header/package.json
packages/universal-header/src/components/tab-bar.js
yarn.lock

[[維運] 手機 icon 未即時顯示問題](https://www.notion.so/twreporter/icon-33860a6d7a0c4e59973ea716e01cbbbb?pvs=4)
N/A

fix: use material symbol svg on tab bar

---

packages/redux/src/actions/receipt.js
packages/redux/src/constants/api-endpoints.js

[[電子收據] 個人專區 / 贊助紀錄: 新增年度收據下載-後端＋串接](https://www.notion.so/twreporter/f812c7b0c6ec47618310d8f3f03eb5ed?pvs=4)
https://github.com/twreporter/go-api/pull/807

feat: add yearly receipt actions

---

packages/react-article-components/src/components/body/annotation.js
packages/react-article-components/src/components/body/blockquote.js
packages/react-article-components/src/components/body/centered-quote.js
packages/react-article-components/src/components/body/list.js
packages/react-article-components/src/components/body/tracking-section.js

[[維運]「後續／迴響」字級異常](https://www.notion.so/twreporter/15f8dbdca93280e39588f27d0604c2bd?pvs=4)
N/A

fix: font-size in tracking section should be 16px

---

packages/core/src/constants/category-set.js

[[hotfix] 改錯字-污→汙](https://www.notion.so/twreporter/hotfix-18f8dbdca9328031bf6fd37b1edd5fc6?pvs=4)

fix: category typo

---

packages/react-components/src/footer/constants/links.js

[[維運]更新 footer / podcast 連結](https://www.notion.so/twreporter/footer-podcast-1848dbdca93280a580b8e08711e3f193?pvs=4)
N/A

fix: update footer podcast link

---

packages/react-components/package.json
packages/react-components/tsconfig.json
yarn.lock

- fix ts import cannot find H4 components
- the generated `.d.ts` is incorrect
N/A

chore: remove ts config for react-components

---

packages/universal-header/src/constants/actions.js

[[維運]header的訂閱改成電子報](https://www.notion.so/twreporter/header-1998dbdca9328081ae0be9b1475caca7?pvs=4)
N/A

fix: action subscribe btn wording

---

packages/react-components/src/icon/index.js
packages/react-components/src/icon/stories/back.stories.js
packages/react-components/src/icon/stories/fullscreen.stories.js
packages/react-components/src/icon/stories/more.stories.js

related to [[議會透視板] 首頁側欄-前端](https://www.notion.so/twreporter/1a48dbdca93280918981dba55c856c58?pvs=4)
N/A

feat: add `fullscreen`, `back`, `more` icons

---

packages/react-components/src/icon/index.js
packages/react-components/src/icon/stories/openInNew.stories.js

add new icon for congress-dashboard legislator page

feat: add icons for congres dashboard

---

packages/react-components/src/empty-state/index.js

fix: buttonOnclick typo

---

packages/core/src/constants/feature-flag.js

feature toggle for offline donation

feat(core): add offline donation feature toggle

---

packages/core/src/constants/feature-flag.js

feat(core): turn off offline donation

---

packages/redux/src/reducers/__test__/mocks/user.js
packages/redux/src/reducers/user.js

[[維運] 專屬回饋頁新增定期定額身份區塊](https://www.notion.so/twreporter/2308dbdca9328005b307c214535cc202?source=copy_link)
N/A

feat: add `isPeriodicPatron` to user state & test

---

packages/core/src/constants/feature-flag.js

feat(core): close lawmaker flag

---

packages/core/src/constants/fundraising.js

[[維運] footer 新增勸募期間](https://www.notion.so/twreporter/footer-24c8dbdca93280a4aeffd5f387f92fe6?source=copy_link)
[[觀測站優化] footer 修改](https://www.notion.so/twreporter/footer-2498dbdca93280c08ff4ebd0376a1e9c?source=copy_link)

feat(core): new fundraising text

---

packages/core/src/constants/external-links.js
packages/core/src/constants/feature-flag.js
packages/index-page/src/components/new-donation-box-section.js
packages/index-page/src/index.js
packages/react-article-components/package.json
packages/react-article-components/src/components/donation-box.js
yarn.lock

[[十週年] 贊助頁首頁banner](https://www.notion.so/twreporter/banner-2428dbdca93280809014ccdd3073d45d?source=copy_link)
[[十週年] 首頁、文章頁、贊助流程](https://www.notion.so/twreporter/23b8dbdca93280d3ad16f684fa23aae8?source=copy_link) 的首頁和文章頁贊助框

feat(core): 10 year anniversary feature flag
